### ISSUE TITLE
Rate req

### ISSUE THREAD

**Issue by titusvh** [HAN-ASD-DT/tm-assignment-titusvh#1]
@dvberkel Can you rate this please?
(master = is this 1st assignment, successive assignments will be performed in branches and use pull requests for rating).

**Comment by titusvh** [comment]
> A Big-O for `n(n+1)` is `n^2`.
> 
> Does this make sense
To be honest I ran away from this limit calculation because of the recursion and the fact that the last time I did those calculations were around 1992, the invitation from my wife to finish the evening with a La Casa del Papel episode seemed a welcome excuse to quit. But looking again, actually is is indeed quite simple.

I understand that n get insignificant compared to n^2 when n gets to infinity. However, what is the criterium to just leave the n in n^2+n away? How insignificant may a part be to accept to disregard it?

**Comment by dvberkel** [comment]
Taking a break and spending some time with your with seems like a good decision.

Sometimes you need some time away from a problem and let your sub-conscience have a go at it.

> I understand that n get insignificant compared to n^2 when n gets to infinity. However, what is the criterium to just leave the n in n^2+n away? How insignificant may a part be to accept to disregard it?

You could think about it in a different way. It is not that you leave n out, you replace it with something that is bigger. When n > 1 then n^2 > n since we multiple both sides of the inequality with n which is bigger than 1.
In similar vain, n^2 + n < n^2 + n^2 = 2n^2 because n^2 > n as we have just discovered.

Seen this way we don't leave n out, we over-estimate it with something that "works" for us, i.e. we can collect like terms.

**Comment by titusvh** [comment]
It is clear to me now. As the Big O is about n->infinity and then even n^5 would be insignificant compared to n^6.
